# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.12'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YoriFulgcuh5ONA8AEzRE8/OUdQ1IUAXCW0OuJ9AS5POaJnMV5I0NECPzcE4b9XKt9HXv5UrROJCcP3IVF9yQJTy+5bvXbF3dsCKEqlSHogGTmzyHOIOy+ZiY3AGdOtlPpXne2GUBp6bcUeiVJLkkiyeUCo49qKBVOy60B8iIx20tke+ETitr7+5FOVN6RcFk8VE2MmCKui9WQ6jMZcLEMgfNfwRRwR14P9DHQlQIUxmn/d0cZBkh6s3IEqtNXY5zxbbd9C0/SacsWQKIwghMi+AqCA+MtjurAlk9GzXjcdXKUJgtwoF5GmlJgjw2tcCBGr2Hmvv/sMd3EVflMQcPWmbDTfDGGSpJ4caRbDEHUlOpirXYkv4VbqlzLPOchgPW4g+zydgYxJx5ZJsnF6A1mJx8g6Qo74cgHhKqAs71cLkALlIrda1A/U5HUght8CkECwKlz4eimOS2gEL0rda7S9dQAR3vx057sQsVT4pjsOTkTSBN+r64s1eVUv8obzyY/+FHiTJNpHWXYOMCD5ubam/cIQ3gAeyIyqGtjtPdbmEyaxIbADII1a7Ey0dVwD07aw0jxOBrkKI5DGLCOjaoRy5jBzp4yaT0YwpDopQ2kwRzOzCmc1Hx6ABa+9Tk2de2tlYKAOYQqpIS/aAJ17EZxx6vmxrblrcRYurHIPJdWo=
    # SAUCE_TOKENS
    - secure: yMJgJb0ydxtl6KKlTdUFvVDnEzv3atgNe6YsBQSl25/X89ATtGuA9jeeNk9R3w5d0k59xcLh5kM1qg38WITESAK1AxatuiifjKqXz8X3aryxFTTKNYXnFFkiRd+CFr5AK4MJoxv2eGPiH9M7ytmr3vn4UK3I/YMDb/aliN10L1jZi/0JCf4IYrHsd+caBKo+EQm2q/OZyMMGGt5KPMscF5eTV/R5MrN+bz+Ix1qmkagjzzJykN6Ug8CWIh+U5OkpWYm+C75rjytnWKSpoU93y8uCneGlez8C0UHvds0LmM2s4QDXIa3A2IsjJ++ixIUZu/ZaKEUsrmaaxESonbH21CwnF4F+/RcMC3Azk7vX7JTqon5LKYry0RDKENEzpB2NHkpuauteC20ACjKaJE6SZ5ML6VmIWqNZSICbqE1uMrIxn7i5wdaNfUkc20OrmtJwg96nCcv3rMuHX6S85LRhJBP23hefTQhIaHQxsAzB9W0chmupNO/CScfJ+yutIXhd1GF+E377XPA1JhkZOgNfFBClnGH3x71QWFCfHeMOiesJi8u8xSla+hSoEaPBaWM1cnP+DyuJGiv2TO7G2mtBjkz06bgkDVS/2Fly5LxH5/Y/+saWseoyHa3Ckcm50EnDX9IoGrlcwh4ISV7soFMK6sV/6onmNB+HaLtMj9vsdXI=
    - secure: Z3bVs3TbJrfYx9m8HTZN4QJ8ZV6feORR6I2KipENiCxEpTXpdS8HxkEjS6rEuHB8rK9gfigSc6EPGX/Xv/PQgAtrF1Nh0R9+5NAQX8/N3CaYZnSagh4PnlDVO3dS9FzHZIrxFcjjMXyvJArIlBMWvLLldhIM2Dcoo1VLsOWhLhYi916LFzDVOtU3sk5uNNl4ZDL/lE4oulSJj2byEFfY4htLPpxMyaljF//VMSjkGm3PFQWyR2cDtk+stHfU1IkRq4busU55iuDSNhOC+mekWnHpeegl7L1Bx8wOen8M4a1ATvbi/txSkrpnjEqP1cr9Fs3mPU+SP/FuEJ6zfaXRYf8UxccD0xtXs48CWuGiWzqii7WOaq7NSzUxGEeoIoZPR/SNu1fl7fM2Tyz/M1jJ4nydR90yGClWq4zeLsiW3VOF7CvsW2JCFPJnoaD7rerjGnEBjczfTTOP3YWICazO+jvevFbndJCEGgMdoCwHJNKohVzxnknN/AfX+iQ79fRWKJo5wvNcNBWGwfVOdUlUyRpedpGefqtfbmPWIvKp5GDH+KePVX1kXhqcmel699+PKCOCS+keACNCNU8EOal2w0nnwHeinWLNWATXWRs31k+hKT+5VsVqOKz2lfIvHAxmKxujErnhnxnOeC+ZIRGvB6nOykvAWU0Z5NcyZ4a69xQ=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: ukc4cA85hWpGaYg4aKyI9kPsovFU3V0Y6mclBQJvOGXCiU/h/+OUWy/BjmyJ93LA+pS7GykNPJYciYlHELRdBNTEMBhlrINhuv9EfFONQK/BlW5/uyuy1p/DurpippKdlxp9hDhd9jSAqMpuuXb44QFOolHOz0BmiU5HQh41jDaYDmPBopgr86Hw+BhCWU6v5Q7+lJ1eNxAdUis4mfsdmzQ/XOHRopfs0kbYXi8h72Kg5Y9GmBHcr0+lnDL+ECWVD/ZgjyujkNe3pIe42iQnLYTAfRba9NqeAx+syhgFXXGLW/DfZJlGvXf6bCRvwrK8sIRBWGyS4I5d9jzPgcaETA6pLBUbZjWEFNPjOah3CqJzCfZIwCttvrLBCcczOJ0Sq6zgRnO07mCSLs36TPl+6t6bQS8e7Ces3VpeNq3Mdq0VN3BpDSKUAofvToT8QQoG1PZ1CRyX9P6C+UEkne8zyf9ej0LxPHFYrlp+OmcK0wYUnn6PCa9QuzJwBYoJtOTmTlLS87Kfko9M4y2AxRVEPoMymO5cns7yg1Ibjlhwcs0WZRkC/fkt12RG+bIex2Q3zfXJ8nG4I2Eard+skRNcOKvR01VF40294h49O3BH+EvATv3QU+Nb9ltpDhKiVFxBAsWnuWfeNRRRgOQ9WS3BcK59DpbYeLhTkysU19w0VhU=

# Cloud testing
# after_deploy:
#   - npm install
#   - npm run test-cloud
#
# Disabled(due to Mixed Content):
#   http://qiita.com/59naga/items/b7a6c5674196181798a6#%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%83%86%E3%82%B9%E3%83%88 
